FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

# Define a pasta padrão dentro do container
WORKDIR /app

# 1. Copia os scripts para dentro da imagem PRIMEIRO
COPY app/ .

# 2. Dá permissão de execução para eles
RUN chmod +x /app/instalacao.sh /app/iniciar.sh

# 3. Instala dependências, RODA O SCRIPT DE INSTALAÇÃO e limpa o lixo
# O ./instalacao.sh é executado aqui para o plugin ficar gravado na imagem
RUN apt-get update && apt-get install -y \
    cups \
    cups-client \
    sane-utils \
    hplip \
    printer-driver-hpcups \
    wget \
    usbutils \
    python3 \
    dbus \
    && ./instalacao.sh \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# 4. Define o comando que roda quando o container liga
CMD ["/app/iniciar.sh"]
